model_path: "/glade/p/cisl/aiml/dgagne/SD_long_2000_50/"
model_file_start: "SD_long_2000_50.cam.h1"
model_file_end: "nc"
time_var: "time"
staggered_variables: ["RHO_CLUBB"]
out_variables: ["P0", "PS", "depth", "row", "col", "hyam", "hybm", "pressure", "temperature", "RHO_CLUBB_lev",
                "RHO_CLUBB_top", "RHO_CLUBB_bottom",
                "QC_sd_in", "NC_sd_in", "QR_sd_in", "NR_sd_in",
                "lamc", "lamr", "lcldm", "n0r", "pgam", "precip_frac",
                "qctend_MG2", "qctend_sd", "nctend_MG2", "nctend_sd",
                "qrtend_MG2", "qrtend_sd", "nrtend_MG2", "nrtend_sd",
                "QC_sd_out", "NC_sd_out", "QR_sd_out", "NR_sd_out",
                "QC_MG2_out", "NC_MG2_out", "QR_MG2_out", "NR_MG2_out"]
subset_variable: ["QC_sd_in"]
subset_threshold: [1.0e-38]
out_path: "/glade/p/cisl/aiml/dgagne/cam_mp_files_sd_parquet/"
out_start: "cam_mp_data_sd"
out_format: "parquet"
