data_path: "/glade/p/cisl/aiml/dgagne/cam_mp_files_run5_full_csv/"
out_path: "/glade/p/cisl/aiml/ggantos/micro/optuna/tau_tenperc_noprune_prune/best_tenperc/"
subset_data:
  train_date_start: 861
  train_date_end: 8800
  test_date_start: 8856
  test_date_end: 17466
random_seed: 328942
subsample: 0.10
classifier_metrics: ["acc", "pss", "hss"]
regressor_metrics: ["mse", "mae", "r2", "hellinger"]
input_cols: ["QC_TAU_in", "NC_TAU_in", "QR_TAU_in", "NR_TAU_in", "RHO_CLUBB_lev",
             "lamc", "lamr", "lcldm", "n0r", "pgam", "precip_frac"]
output_cols: ["qrtend_TAU", "nctend_TAU", "nrtend_TAU"]
input_transforms:
  QC_TAU_in: "log10_transform"
  NC_TAU_in: "log10_transform"
  QR_TAU_in: "log10_transform"
  NR_TAU_in: "log10_transform"
  lamc: "log10_transform"
  lamr: "log10_transform"
  pgam: "log10_transform"
  n0r: "log10_transform"
input_scaler: "StandardScaler"
output_transforms:
  qrtend_TAU:
    0: ["<=", 1e-18, "zero_transform", "None"]
    1: [">", 1e-18, "log10_transform", "StandardScaler"]
  nctend_TAU:
    0: [">=", -1e-18, "zero_transform", "None"]
    1: ["<", -1e-18, "neg_log10_transform", "StandardScaler"]
  nrtend_TAU:
    -1: ["<", 0, "neg_log10_transform", "StandardScaler"]
    0: ["==", 0, "zero_transform", "None"]
    1: [">", 0, "log10_transform", "StandardScaler"]
classifier_networks:
  hidden_layers: 6
  hidden_neurons: 57
  loss: "categorical_crossentropy"
  output_activation: "softmax"
  activation: "relu"
  epochs: 10
  batch_size: 1024
  verbose: 2
  lr: 0.0022312585197192653
  l2_weight: 0.0043886219635457845
  classifier: 1
  metrics: ["accuracy", "heidke", "peirce", "confusion"]
regressor_networks:
  hidden_layers: 6
  hidden_neurons: 100
  loss: "huber"
  output_activation: "linear"
  activation: "relu"
  epochs: 10
  batch_size: 1024
  verbose: 2
  lr: 0.004783023448317777
  l2_weight: 1.2542008583363183e-05
  classifier: 0
  metrics: ["rmse", "mae", "r2", "hellinger"]

