model_path: "/glade/p/cisl/aiml/dgagne/TAU_run5_full/"
model_file_start: "TAU_run5.cam.h1"
model_file_end: "nc"
time_var: "time"
time_split_interval: 1
staggered_variables: ["RHO_CLUBB"]
out_variables: ["P0", "PS", "depth", "row", "col", "hyam", "hybm", "pressure", "temperature", "RHO_CLUBB_lev",
                "RHO_CLUBB_top", "RHO_CLUBB_bottom",
                "QC_TAU_in", "NC_TAU_in", "QR_TAU_in", "NR_TAU_in",
                "lamc", "lamr", "lcldm", "n0r", "pgam", "precip_frac",
                "qctend_MG2", "qctend_TAU", "nctend_MG2", "nctend_TAU",
                "qrtend_MG2", "qrtend_TAU", "nrtend_MG2", "nrtend_TAU"]
subset_variable: ["QC_TAU_in", "QR_TAU_in"]
subset_threshold: [1.0e-18, 1.0e-18]
out_path: "/glade/p/cisl/aiml/dgagne/cam_mp_files_run5_full_csv/"
out_start: "cam_mp_data_run5"
out_format: "csv"
