model_path: "/glade/p/cisl/aiml/dgagne/SD_long_2000_50/"
model_file_start: "SD_long_2000_50.cam.h1"
model_file_end: "nc"
time_var: "time"
time_split_interval: 50
staggered_variables: ["RHO_CLUBB"]
out_variables: ["P0", "PS", "depth", "row", "col", "hyam", "hybm", "pressure", "temperature", "RHO_CLUBB_lev",
                "RHO_CLUBB_top", "RHO_CLUBB_bottom",
                "QC_sd_in", "NC_sd_in", "QR_sd_in", "NR_sd_in",
                "lamc", "lamr", "lcldm", "n0r", "pgam", "precip_frac",
                "qctend_MG2", "qctend_sd", "nctend_MG2", "nctend_sd",
                "qrtend_MG2", "qrtend_sd", "nrtend_MG2", "nrtend_sd"]
subset_variable: ["QC_sd_in", "QR_sd_in"]
subset_threshold: [1.0e-18, 1.0e-18]
out_path: "/glade/p/cisl/aiml/ggantos/cam_mp_files_sd_50_csv/"
out_start: "cam_mp_data_sd"
out_format: "csv"
