data:
  data_path: "/glade/p/cisl/aiml/dgagne/cam_mp_files_run7_parquet/"
  scratch_path: "/glade/scratch/dgagne/cam_mp_run7_quantile_nn/"
  out_path: "/glade/work/dgagne/cam_mp_run7_quantile_nn/"
  input_cols: ["QC_TAU_in", "QR_TAU_in", "NC_TAU_in", "NR_TAU_in"]
  output_cols: ["qctend_TAU", "qrtend_TAU", "nctend_TAU", "nrtend_TAU"]
  qc_thresh: 1e-12
  n_quantiles: 500
  subsample: 1
  random_seed: 215689
  subset_data:
    train_date_start: 0
    train_date_end: 6000
    test_date_start: 6001
    test_date_end: 10000
    validation_frequency: 3

model:
  hidden_layers: 2
  hidden_neurons: 200
  activation: "relu"
  output_activation: "sigmoid"
  loss: "mse"
  lr: 0.001
  batch_size: 1024
  epochs: 100
  verbose: 2

