data_path: "/glade/p/cisl/aiml/ggantos/cam_mp_files_sd_full_csv/"
out_path: "/glade/p/cisl/aiml/ggantos/micro/optuna/run_full"
subset_data:
  train_date_start: 5
  train_date_end: 7000
  test_date_start: 7005
  test_date_end: 8760
random_seed: 328942
subsample: 1.0
classifier_metrics: ["acc", "pss", "hss"]
regressor_metrics: ["mse", "mae", "r2", "hellinger"]
input_cols: ["QC_sd_in", "NC_sd_in", "QR_sd_in", "NR_sd_in", "RHO_CLUBB_lev",
             "lamc", "lamr", "lcldm", "n0r", "pgam", "precip_frac"]
output_cols: ["qrtend_sd", "nctend_sd", "nrtend_sd"]
input_transforms:
  QC_sd_in: "log10_transform"
  NC_sd_in: "log10_transform"
  QR_sd_in: "log10_transform"
  NR_sd_in: "log10_transform"
  lamc: "log10_transform"
  lamr: "log10_transform"
  pgam: "log10_transform"
  n0r: "log10_transform"
input_scaler: "StandardScaler"
output_transforms:
  qrtend_sd:
    0: ["<=", 1e-18, "zero_transform", "None"]
    1: [">", 1e-18, "log10_transform", "StandardScaler"]
  nctend_sd:
    0: [">=", -1e-18, "zero_transform", "None"]
    1: ["<", -1e-18, "neg_log10_transform", "StandardScaler"]
  nrtend_sd:
    -1: ["<", 0, "neg_log10_transform", "StandardScaler"]
    0: ["==", 0, "zero_transform", "None"]
    1: [">", 0, "log10_transform", "StandardScaler"]
classifier_networks:
  hidden_layers: 3
  hidden_neurons: 56
  loss: "categorical_crossentropy"
  output_activation: "softmax"
  activation: "leaky"
  epochs: 10
  batch_size: 4096
  verbose: 1
  lr: 0.006433969868319847
  l2_weight: 0.000001697117746685373
  classifier: 1
regressor_networks:
  hidden_layers: 3
  hidden_neurons: 46
  loss: "mse"
  output_activation: "linear"
  activation: "relu"
  epochs: 10
  batch_size: 4096
  verbose: 1
  lr: 0.0011382474317559797
  l2_weight: 0.0007140306741411703
  classifier: 0

