log: True
save_path: "/glade/work/wchuang/mlmicrophysics/tau_run_11_nrtend_retrain_lev/echo_quantile/log"

pbs:
  jobs: 20
  bash: ["source ~/.bashrc", "conda activate mlmicro"]
  batch:
    l: ["select=1:ncpus=16:ngpus=1:mem=384GB", "walltime=06:00:00", "gpu_type=a100"]
    A: "P93300606"
    q: "develop"
    N: "echo_trial"
    o: "echo_trial.out"
    e: "echo_trial.err"
    k: "eod"

optuna:
  study_name: "micro-quantile"
  storage: "micro_quantile.db"
  storage_type: "sqlite"
  objective: "/glade/u/home/wchuang/mlmicrophysics/mlmicrophysics/objective.py"
  direction: "maximize"
  metric: "val_loss"
  n_trials: 900
  gpu: a100
  save_path: "/glade/work/wchuang/mlmicrophysics/tau_run_11_nrtend_retrain_lev/echo_quantile"
  sampler:
    type: "TPESampler"
    n_startup_trials: 100
  parameters:
    model:hidden_layers:
      type: "int"
      settings:
        name: "hidden_layers"
        low: 1
        high: 3
    model:hidden_neurons:
      type: "int"
      settings:
        name: "hidden_neurons"
        low: 32
        high: 4096 
    model:lr:
      type: "loguniform"
      settings:
        name: "lr"
        low: 0.0001
        high: 0.01
    data:n_quantiles:
      type: "int"
      settings:
        name: "n_quantiles"
        low: 500
        high: 4000
