log:
  save_path: "/glade/p/cisl/aiml/dgagne/micro/optuna/quantile/log.txt"

slurm:
  jobs: 20
  bash: ["source ~/.bashrc", "conda activate mlmicro"]
  batch:
    account: "NAML0001"
    l: ["select=1:ncpus=4:mem=64GB", "walltime=06:00:00"]
    A: "NAML0001"
    q: "casper"
    N: "echo_trial"
    o: "echo_trial.out"
    e: "echo_trial.err"

optuna:
  name: "micro_quantile.db"
  reload: 0
  objective: "/glade/u/home/dgagne/mlmicrophysics/mlmicrophysics/objective.py"
  direction: "minimize"
  metric: "val_loss"
  n_trials: 900
  gpu: 0
  save_path: "/glade/p/cisl/aiml/dgagne/micro/optuna/quantile/"
  sampler:
    type: "TPESampler"
    n_startup_trials: 100
  parameters:
    model:hidden_layers:
      type: "int"
      settings:
        name: "hidden_layers"
        low: 1
        high: 6
    model:hidden_neurons:
      type: "int"
      settings:
        name: "hidden_neurons"
        low: 32
        high: 2048
    model:lr:
      type: "loguniform"
      settings:
        name: "lr"
        low: 1e-6
        high: 1e-2
