data:
  data_path: "/glade/scratch/wchuang/mlmicrophysics/cam_ml_ported5_tau2/20230713"
  scratch_path: "/glade/scratch/wchuang/mlmicrophysics/tau_run_7/20230713_echo_quantile_8paramoptimized"
  out_path: "/glade/work/wchuang/mlmicrophysics/tau_run_7/echo_quantile_8paramoptimized"
  input_cols: ["QC_TAU_in", "QR_TAU_in", "NC_TAU_in", "NR_TAU_in", "RHO_CLUBB", "T", "CLOUD", "FREQR"]
  output_cols: ["qctend_TAU", "qrtend_TAU", "nctend_TAU", "nrtend_TAU"]
  qc_thresh: 1e-8
  n_quantiles: 2322 
  subsample: 0.01
  random_seed: 215689
  subset_data:
    train_date_start: 0
    train_date_end: 6000
    test_date_start: 6001
    test_date_end: 10000
    validation_frequency: 3

model:
  hidden_layers: 1
  hidden_neurons: 2021 
  activation: "relu"
  output_activation: "sigmoid"
  loss: "mse"
  lr: 0.000893
  batch_size: 1024
  epochs: 50 # default 100
  verbose: 2

callbacks:
  EarlyStopping:
    monitor: "loss"
    patience: 5
    mode: "min"
    verbose: 0
  ReduceLROnPlateau: 
    monitor: "loss"
    factor: 0.1
    patience: 2
    min_lr: 1.0e-12
    min_delta: 1.0e-08
    mode: "min"
    verbose: 0
  CSVLogger:
    filename: "training_log.csv"
    separator: ","
    append: False
  ModelCheckpoint:
    filepath: "model.h5"
    monitor: "loss"
    save_weights: True
    save_best_only: True
    mode: "min"
    verbose: 0
